version: "3"

services:
  redis:
    image: redis:latest
  yaxc:
    image: darmiel/yaxc:latest
    command: serve --enable-encryption -x 86400 -l 5s -s 1h -r redis:6379 --proxy-header X-Forwarded-For
    ports:
      - 1332:1332
    depends_on:
      - redis
    restart: on-failure
    labels:
      - "com.centurylinklabs.watchtower.scope=yaxcscope"
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope yaxcscope
    labels:
      - "com.centurylinklabs.watchtower.scope=yaxcscope"
    restart: on-failure